version: "3"

services:
  api:
    container_name: mini-api-container
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "80:80"
    volumes:
      - ./app:/code/app
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=miniatures-site
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-db: